service: basic-serverless-lambda-python-Test

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1


layers:
  python.zip:
    path: /home/sxinaganti/github-to-lambda/ 
    name: python-test
    description: serverless-layer

functions:
  lambda:
    name: test-lambda
    handler: lambda_function.handler
    description: test-lambda
    timeout: 5