service: basic-serverless-lambda-python

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1


functions:
  lambda:
    name: test-lambda
    handler: lambda_function.handler
    description: test-lambda
    timeout: 5
    memorysize: 128