service: basic-serverless-lambda-python-Test

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  custom: ${file(./api_config.yml)}
  layers:
    - arn:aws:lambda:us-east-1:947072271903:layer:smart_yml:2

functions:
  lambda_function:
    name: test-lambda
    handler: lambda_function.handler
    description: test-lambda
    timeout: 5
    package:
      # Directories and files to include in the deployed package
      # Explicitly set the package artifact to deploy (overrides native packaging behavior)
      artifact: ovt-vmi-dev1/code/MultiDaySale/multidaysale_api.zip
      # Package this function as an individual artifact (default: false)
      individually: true
    # ARN of Lambda layers to use
    events:
      - s3:
          bucket: ovt-vmi-dev1
          event: s3:ObjectCreated:*
          rules:
            - prefix: Landing/ MultiDaySale/
            - suffix: .csv
          # Set to 'true' when using an existing bucket
          # Else the bucket will be automatically created
          existing: true
          # Optional, for forcing deployment of triggers on existing S3 buckets
          forceDeploy: true

