service: basic-serverless-lambda-python-Test

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1

functions:
  lambda:
    name: test-lambda
    handler: lambda_function.handler
    description: test-lambda
    layers:
      - arn:aws:lambda:us-east-1:947072271903:layer:smart_yml:2
    timeout: 5