service: basic-serverless-lambda-python-Test

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1


layers:
  hello:
    path: python.zip
    description: serverless-layer

functions:
  lambda:
    name: test-lambda
    handler: lambda_function.handler
    description: test-lambda
    timeout: 5