service: basic-serverless-lambda-python-Test

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  layers:
    - arn:aws:lambda:us-east-1:947072271903:layer:smart_yml:2
functions:
  lambda_function:
    name: test-lambda
    handler: lambda_function.handler
    description: test-lambda
    timeout: 5